-- MySQL Script generated by MySQL Workbench
-- Fri Sep 30 01:34:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema appdroid
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema primer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema primer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `primer` DEFAULT CHARACTER SET utf8 ;
USE `primer` ;

-- -----------------------------------------------------
-- Table `primer`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primer`.`categories` (
  `category_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_id` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `primer`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primer`.`customers` (
  `customer_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_fname` VARCHAR(100) NOT NULL,
  `customer_lname` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_id` (`customer_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `primer`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primer`.`products` (
  `product_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `manufacturer_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `category_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `primer`.`categories` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `primer`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primer`.`stores` (
  `store_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`store_id`),
  UNIQUE INDEX `store_id` (`store_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `primer`.`deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primer`.`deliveries` (
  `product_id` BIGINT UNSIGNED NOT NULL,
  `store_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `delivery_date` DATE NOT NULL,
  `product_count` INT UNSIGNED NOT NULL,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `store_id` (`store_id` ASC) VISIBLE,
  CONSTRAINT `deliveries_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `primer`.`products` (`product_id`),
  CONSTRAINT `deliveries_ibfk_2`
    FOREIGN KEY (`store_id`)
    REFERENCES `primer`.`stores` (`store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `primer`.`price_change`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primer`.`price_change` (
  `product_id` BIGINT UNSIGNED NOT NULL,
  `date_price_change` DATE NOT NULL,
  `new_price` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`product_id`, `date_price_change`),
  CONSTRAINT `price_change_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `primer`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `primer`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primer`.`purchases` (
  `purchase_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT UNSIGNED NOT NULL,
  `store_id` BIGINT UNSIGNED NOT NULL,
  `purchase_date` DATETIME NOT NULL,
  PRIMARY KEY (`purchase_id`),
  UNIQUE INDEX `purchase_id` (`purchase_id` ASC) VISIBLE,
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `store_id` (`store_id` ASC) VISIBLE,
  CONSTRAINT `purchases_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `primer`.`customers` (`customer_id`),
  CONSTRAINT `purchases_ibfk_2`
    FOREIGN KEY (`store_id`)
    REFERENCES `primer`.`stores` (`store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `primer`.`purchase_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primer`.`purchase_items` (
  `purchase_id` BIGINT UNSIGNED NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `product_count` BIGINT UNSIGNED NOT NULL,
  `product_price` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`purchase_id`, `product_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `purchase_items_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `primer`.`products` (`product_id`),
  CONSTRAINT `purchase_items_ibfk_2`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `primer`.`purchases` (`purchase_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
